from string import ascii_letters
SHIFT_KEY = "Key.shift"
DEFAULT_LOG_ID = "A000"

shifted_number_keys = {
    '1': '!', '2': '@', '3': '#', '4': '$', '5': '%',
    '6': '^', '7': '&', '8': '*', '9': '(', '0': ')'
}

# Define the mapping for shifted punctuation characters
shifted_punctuation = {
    '`': '~', '-': '_', '=': '+', '[': '{', ']': '}',
    '\\': '|', ';': ':', '\'': '"', ',': '<', '.': '>', '/': '?'
}

# Combine the shifted number keys and punctuation into a single dictionary
shifted_values = {**shifted_number_keys, **shifted_punctuation}

# Create a mapping for all alphabetic characters to their uppercase equivalents
shift_mapping = {char: char.upper() for char in ascii_letters}

# Update the shift_map with the shifted values for numbers and punctuation
shift_mapping.update(shifted_values)

SHIFT_MAP = shift_mapping
ALL_CODES = [
    'a',
    's',
    'd',
    'f',
    'h',
    'g',
    'z',
    'x',
    'c',
    'v',
    'b',
    'q',
    'w',
    'e',
    'r',
    'y',
    't',
    '1',
    '2',
    '3',
    '4',
    '6',
    '5',
    '=',
    '9',
    '7',
    '-',
    '8',
    '0',
    ']',
    'o',
    'u',
    '[',
    'i',
    'p',
    'l',
    'j',
    "'",
    'k',
    ';',
    '\\',
    ',',
    '/',
    'n',
    'm',
    '.',
    '`',
    '[decimal]',
    '[asterisk]',
    '[plus]',
    '[clear]',
    '[divide]',
    '[enter]',
    '[hyphen]',
    '[equals]',
    '0',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '[return]',
    '[tab]',
    ' ',
    '[del]',
    '[esc]',
    '[right-cmd]',
    '[left-cmd]',
    '[left-shift]',
    '[caps]',
    '[left-option]',
    '[left-ctrl]',
    '[right-shift]',
    '[right-option]',
    '[right-ctrl]',
    '[fn]',
    '[f17]',
    '[volup]',
    '[voldown]',
    '[mute]',
    '[f18]',
    '[f19]',
    '[f20]',
    '[f5]',
    '[f6]',
    '[f7]',
    '[f3]',
    '[f8]',
    '[f9]',
    '[f11]',
    '[f13]',
    '[f16]',
    '[f14]',
    '[f10]',
    '[f12]',
    '[f15]',
    '[help]',
    '[home]',
    '[pgup]',
    '[fwddel]',
    '[f4]',
    '[end]',
    '[f2]',
    '[pgdown]',
    '[f1]',
    '[left]',
    '[right]',
    '[down]',
    '[up]',
    '[unknown]']

LEFT_SHIFT = "[left-shift]"
RIGHT_SHIFT = "[right-shift]"

SHIFT_CODES = {LEFT_SHIFT: "Key.shift",
               RIGHT_SHIFT: "Key.shift"}
CODES = {
    "[del]": "Key.backspace",
    "[return]": "Key.enter",
    "[tab]": "Key.tab",
    "[caps]": "Key.caps_lock",
}
BEGIN_SPECIAL_KEY = "["
END_SPECIAL_KEY = "]"
BANNED_CODES = ['[decimal]',
                '[asterisk]',
                '[plus]',
                '[clear]',
                '[divide]',
                '[enter]',
                '[hyphen]',
                '[equals]',
                '[esc]',
                '[right-cmd]',
                '[left-cmd]',
                '[left-option]',
                '[left-ctrl]',
                '[right-option]',
                '[right-ctrl]',
                '[fn]',
                '[f17]',
                '[volup]',
                '[voldown]',
                '[mute]',
                '[f18]',
                '[f19]',
                '[f20]',
                '[f5]',
                '[f6]',
                '[f7]',
                '[f3]',
                '[f8]',
                '[f9]',
                '[f11]',
                '[f13]',
                '[f16]',
                '[f14]',
                '[f10]',
                '[f12]',
                '[f15]',
                '[help]',
                '[home]',
                '[pgup]',
                '[fwddel]',
                '[f4]',
                '[end]',
                '[f2]',
                '[pgdown]',
                '[f1]',
                '[left]',
                '[right]',
                '[down]',
                '[up]',
                '[unknown]']
